[tox]
envlist = py38

[testenv]
deps=-r{toxinidir}/requirements.txt
     -r{toxinidir}/test-requirements.txt

commands=
   nosetests \
      []

[pytest]
env_files =
    .env
    .test.env
    .deploy.env