import os


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "FILL_ME_IN")
VECTORDB_HOST = os.getenv("VECTORDB_HOST", "FILL_ME_IN")
VECTORDB_PASSWORD = os.getenv("VECTORDB_PASSWORD", "FILL_ME_IN")
VECTORDB_PERSIST_DIRECTORY = os.getenv("VECTORDB_PERSIST_DIRECTORY", "FILL_ME_IN")
VECTORDB_PORT = os.getenv("VECTORDB_PORT", "FILL_ME_IN")
VECTORDB_USERNAME = os.getenv("VECTORDB_USERNAME", "FILL_ME_IN")
